#!/bin/sh
# Copyright (C) 2000-2013 Synology Inc. All rights reserved.

. $(dirname $0)/common

TRAEFIK_CONFIG_FILE="traefik4srm.conf"
TRAEFIK_CONFIG="${SYNOPKG_PKGDEST}/${TRAEFIK_CONFIG_FILE}"
TRAEFIK_USER="$(echo "${SYNOPKG_PKGNAME}" | awk '{print tolower($_)}')"
LOG="${SYNOPKG_PKGDEST}/${TRAEFIK_USER}.log"

echo "[$(date +'%T')] #### Start postinst... ####" >>"${LOG}"

echo "[$(date +'%T')] Linking Traefik binaries" >>"${LOG}"
DO_LINK

if [ "$SYNOPKG_PKG_STATUS" = "INSTALL" ]; then

    echo "[$(date +'%T')] Creating Traefik4srm startup config file at \"${TRAEFIK_CONFIG}\"" >>"$LOG"
    touch "${TRAEFIK_CONFIG}"

    # shellcheck disable=SC2154
    {
        echo "[$(date +'%T')] Setting STATIC_CONFIG_FILE=${wizard_static_config_path} in \"${TRAEFIK_CONFIG}\""
    } >>"$LOG"
    {
        echo "STATIC_CONFIG_FILE=${wizard_static_config_path}"
    } >>"${TRAEFIK_CONFIG}"

elif [ "$SYNOPKG_PKG_STATUS" = "UPGRADE" ]; then

    echo "[$(date +'%T')] Restore Config" >>"${LOG}"

    mv "/tmp/${TRAEFIK_CONFIG_FILE}" "${TRAEFIK_CONFIG}"

fi

echo "[$(date +'%T')] #### Done postinst ####" >>"${LOG}"

exit 0
